language: python
sudo: true
python:
- '3.6'
- '3.5'
- '3.4'
- '2.7'
env: GHOST_VERSION=1

script:
  - pip install nose2 coverage
  - cd tests && ./prepare_tests.sh $GHOST_VERSION ; cd ..
  - nose2 -v -C --coverage-report term-missing

jobs:
  include:
    - &integration-stage
      stage: integration
      env:    GHOST_VERSION=1.18

    - <<: *integration-stage
      env:    GHOST_VERSION=1.17

    - <<: *integration-stage
      env:    GHOST_VERSION=0.11
