language: python
sudo: true
python:
- '3.6'
- '3.5'
- '3.4'
- '2.7'
env: GHOST_VERSION=1

addons:
  sonarcloud:
    organization: "rycus86-github"
    token:
      secure: "EfwBuzdPDXZVYHKyDL0xYv19RxYwrbLuoYaxYM5kN2XgwGxEuTIC8q/xI1jOQvuQ34ptQxKFk39ryAcXWgkAefrfQTJuIb9fJDwb0Hs6VogBwu8BSbAH/tbU97O3/AIQqNlnDJa+omVXqD+Op1G07f0q7UMmZGP1b3sntL12xGGftcx6c6Z3qUnqgdLqNhwp2VGaL+QuoGaFi0Ruqj5oVJaevEIYkfHcPfA851nkeOuVvwZDUay9pSoGREboVKg0HIEvvw7GUMS7rUIG7yv5XwTtUhd1rBmbcxVZSBLRsKFgyIgZrJsfXcYUNfnC2z7CR1Pz7wKxRa57lD8UUYqHBgZXeIV1ywxT1RMMUc+LGpzwcm4XhlsFzoNSC/9jnXzmb9RmdczCIIBSc7+PbvnQODK3IkGsqqEDGrOQ+6DZGGnb0viVzBaKswP3uWl53RTKIbEgte8CBpQmVafDTZQ30Wk/LOAx1ZPOTquafeMW9PwUFR7bjmSZL7BS+wkawRFYsVWATz3Zg7j8Jf0wdKI8n95Lm+juLNQPNjtmrnHEvpYq48tZBVEpnDL8JhqrxbinFDTyNRX8xbCRfvO/MmH3Szn6Obm0+jAsaUXttCh9IdVyNj/28HrrRFx3Sr1XtuhJ6Rv4MJioTT+q9DKjpms5N7nQopVAWade+EvhLHeLbSY="

script:
  # prepare libraries and reporters
  - pip install nose2 coverage pylint coveralls
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C .
  - ./testspace config url rycus86.testspace.com
  # prepare tests
  - cd tests && ./prepare_tests.sh $GHOST_VERSION ; cd ..
  # run the tests
  - |
    nose2 -v \
      --plugin nose2.plugins.junitxml --junit-xml \
      --with-coverage --coverage-report xml --coverage-report term-missing
  - pip install .
after_success:
  # coverage reports
  - |
    if [[ "$(python --version 2>&1)" = *3.6* ]] && [ "$GHOST_VERSION" == "1" ]; then
      coveralls || exit 0
      ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT || exit 0
      ./testspace nose2-junit.xml coverage.xml || exit 0
      pylint src/*.py -r n \
        --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" \
        | tee pylint-report.txt ; echo -n
      sonar-scanner -Dsonar.projectKey=ghost-client -Dsonar.sources=ghost_client \
        -Dsonar.python.xunit.reportPath=nose2-junit.xml \
        -Dsonar.python.coverage.reportPath=coverage.xml \
        -Dsonar.python.pylint.reportPath=pylint-report.txt
    fi

jobs:
  include:
    - &integration-stage
      stage: integration
      env:    GHOST_VERSION=1.22

    - <<: *integration-stage
      env:    GHOST_VERSION=1.20

    - <<: *integration-stage
      env:    GHOST_VERSION=1.17

    - <<: *integration-stage
      env:    GHOST_VERSION=0.11

    - stage: deploy
      script: skip
      deploy:
        provider: pypi
        user: rycus86
        password:
          secure: hvN5/V/EnZL0sl6U+MkGBT2K1PRazvl/g7AAOIpwxuOwixpFv1GOYCXbd9unt3+Q/JVuC1tTrzYEEkZ0MxnA13raLyqZ+viJ3qKpHNLRmG70FiZa3XDFGwTEA/Wj4MsLAKrwgsgwIPYD1rIcsfqxrZ9yCl22CpAC7HaZb6h3WnnBmQ9ERcG8C5MlLDONuHbJOBrKCCcBi9A99Oi681+CvPL6nJ7IOjs6YGsJsqmbu9j+08T7DjxfWkO/swuMPROL2rAIHIjWlZzBEcsqvTsPPbVSPV7SZ5bZE9Gm60ViqTTtsA0erFDUkUKMOF/H8ec5X4R38wQP+oF2yzxW42A08CAfkq6sQXbuhZRNczLlOFfKTlTVaSPARq1A8m7TkCj26jFOHGMSB62RY23wilZUZO1en0iBqqD0sIoRxdupjEIJCggD81XGYYFWQ8cdphoKsfIM6uswAJxnupKLPSPPOn/Ft2fixUfbvmE9XQ+8rDFmZUnW0CZdZpzEW9VSdJNv9hHI8/peSVu2ei+AFt4V2x2nkgNof/FGdH6t7LrvlvxzlviVjU6Fk8bwYF7/1gmgVsQ5i3uZJqyb81KGrDdBHKRZ0hRxhfw2jxjVk9DIEM9Udzp64hqzbCns7S9qqmqhyZpOWcYQ2wxgKRYvuO7L1a0jAwakP9O3hHjmt5hNlno=
        on:
          tags: true

    - stage: verify
      install: skip
      script:
        - pip install ghost-client
